### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by citizenrich** [HL7/fhirpath.js#114]
There's an error on import of fhirpath.js version 2.14.5 in our app. This happens on the initial import. Reverting to 2.7.4 fixes it.
```
> node --max-old-space-size=8192 lib/app.js

/home/gofr/gofr/gofr-backend/node_modules/fhirpath/src/fhirpath.js:339
            toAdd = res.data?.[field];
                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gofr/gofr/gofr-backend/lib/modules/fhirFilter.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by plynchnlm** [comment]
That is the optional chaining operator.  Which version of Node.js are you using?

**Comment by citizenrich** [comment]
Thanks. It's v12.22.9 running on Ubuntu 22. It's the default installed version for that OS. And, pretty old. Let me try a newer one.

**Comment by citizenrich** [comment]
Yep, newer nodejs seems to work just fine.
