### ISSUE TITLE
time/date math bug

### ISSUE THREAD

**Issue by bkaney** [HL7/fhirpath.js#29]
This works:
```
today() + 10 days
[ FP_DateTime { asStr: '2019-12-16' } ]
```

This fails:
```
today() - 10 days
Error: Expected number, got: "2019-11-16"
    at Number (.../node_modules/fhirpath/src/fhirpath.js:335:13)
    at makeParam (.../node_modules/fhirpath/src/fhirpath.js:384:12)
    at infixInvoke (.../node_modules/fhirpath/src/fhirpath.js:445:21)
    at Object.engine.OpExpression (.../node_modules/fhirpath/src/fhirpath.js:488:10)
    at Object.engine.doEval (.../node_modules/fhirpath/src/fhirpath.js:542:22)
    at applyParsedPath (.../node_modules/fhirpath/src/fhirpath.js:570:17)
    at Object.evaluate (.../node_modules/fhirpath/src/fhirpath.js:583:10)
    at client.read.then (.../src/fhirpath.js:19:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by plynchnlm** [comment]
Fix in progress.

**Comment by plynchnlm** [comment]
Fixed on branch fix_date_subtraction; pull request pending.
